version: '3'
services:
  api_ra_events:
    container_name: "api_ra_events"
    build: .
    command: "npm run prod"
    environment:
      - NODE_ENV=production
      - TZ=Europe/London
    image: f4zphp27xi2s27yn/my_repo_topor:ra_events_api
    ports:
      - 8030:8030
networks:
  default:
    name: ra_events_grabber_network
    external: true
